import redis


# r = redis.Redis(host='127.0.0.1', port=6379)
# r.set('name', 'qiye')
# print(r.get('name'))

pool = redis.ConnectionPool(host='127.0.0.1', port=6379)
r = redis.Redis(connection_pool=pool)
r.set('name', 'ling')
print(r.get('name'))
print('****hash****')
r.hset('student', 'name', 'qiye')
print(r.hget('student', 'name'))
r.hmset('student', {'name': 'qiye', 'age': 20})
print(r.hmget('student', 'name', 'age'))
print('****list****')
r.lpush('digit', 11, 22, 33)
r.linsert('digit', 'before', '22', 'aa')
print(r.lrange('digit', 0, 3))
r.lset('digit', 3, 44)
r.lrem('digit', value='aa', count=1)
print(r.lrange('digit', 0, 2))
print('*****set*****')
r.sadd('num', 33, 44, 55, 66)
print(r.scard('num'))
print(r.smembers('num'))
print('*****sorted set*****')
r.zadd('znum', {'num1': 110, 'num2': 22})
print(r.zcard('znum'))
print(r.zrange('znum', 0, 10))
print(r.zscore('znum', 'num1'))
